parser: '@typescript-eslint/parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  project: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  'prettier/prettier': ['error']
