services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spirit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - spirit

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '3001:3000'
    networks:
      - spirit
    env_file:
      - .env.dev
      - path: .env
        required: false
    volumes:
      - ./api:/api
      - /api/node_modules
      - ./common:/common

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - '3000:3000'
    networks:
      - spirit
    env_file:
      - .env.dev
      - path: .env
        required: false
    volumes:
      - ./app:/app
      - /app/node_modules
      - ./common:/common

volumes:
  postgres_data:

networks:
  spirit:
